import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
const inter = Inter({ subsets: ['latin'] })
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
        <script src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
      </Head>
      <main className='bg-[#F5F5F5]'>
        <div className='lg:ml-[6rem]'>
        <img className='lg:float-right sm:float-right' width={650} src="images/hero.png" alt="hero_img" />
        <h1 className='lg:text-6xl text-3xl lg:pt-[16rem] py-3 mx-5'>Want&nbsp;to&nbsp;see&nbsp;a<br /> <span className='text-[#008837]'>Better&nbsp;Oshida?</span></h1>
        <h3 className='text-2xl font-light lg:text-4xl text-[#FFC444] py-3 mx-5'>Let's&nbsp;work&nbsp;together<br />to&nbsp;make&nbsp;it&nbsp;happen</h3>
        <p className='text-lg pb-10 py-5 mx-5'>Odisha is rich in natural resources and strong culture, still our society lags behind others. Instead of sitting and complaining, be the change you want to see in Odisha!</p>
        <a className='bg-[#008837] ml-5 rounded-full text-white px-3 py-2' href="#">Help a Neady</a>
        <a className='bg-[#FFC444] rounded-full  text-white px-3 py-2' href="#">Become a Volunteer</a>
        </div>

        <div className='my-8 lg:mx-6 mx-9 lg:mt-[14rem]'>
          <span className='lg:text-4xl text-2xl break-normal'>Top Compaings</span>
          <a className='lg:text-2xl text-xl float-right text-[#008837]' href="#">See all</a>
        </div>

        <div className='lg:grid lg:grid-cols-2 lg:gap-4 lg:mt-[7rem] mx-4'>
          <div className='bg-white shadow-2xl'>
            <img src="images/campaign-1.png" className='h-[19rem] w-full object-cover object-top' alt="compaign" />
            <div className='px-8 py-8'>
            <span>by Tazim</span>
            <h2 className='text-3xl font-bold'>Lorem Ipsum</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas vel, velit fugit rerum saepe, delectus odit accusantium quod accusamus a fuga, alias harum. Nulla error non dolorem voluptas porro eos.</p>
            <div className="w-full my-6 rounded-full h-2.5 bg-green-50">
            <div className="bg-green-600 h-2.5 w-[45%] rounded-full"></div>
            <p className='py-1'><span className='text-green-600 mx-1 text-lg'>Raised</span><span className='text-xl text-green-600 font-medium'>Rs 18,000</span><span className='float-right'><span className='text-lg'>Goal</span> <span className='text-xl font-medium'>Rs 40,000</span></span></p>
          </div>
            </div>
          </div>

          <div className='bg-white shadow-2xl'>
            <img src="images/campaign-2.png" className='h-[19rem] w-full object-cover object-top' alt="compaign" />
            <div className='px-8 py-8'>
            <span>by Tazim</span>
            <h2 className='text-3xl font-bold'>Lorem Ipsum</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas vel, velit fugit rerum saepe, delectus odit accusantium quod accusamus a fuga, alias harum. Nulla error non dolorem voluptas porro eos.</p>
            <div className="w-full my-6 rounded-full h-2.5 bg-green-50">
            <div className="bg-green-600 h-2.5 w-[45%] rounded-full"></div>
            <p className='py-1'><span className='text-green-600 mx-1 text-lg'>Raised</span><span className='text-xl text-green-600 font-medium'>Rs 18,000</span><span className='float-right'><span className='text-lg'>Goal</span> <span className='text-xl font-medium'>Rs 40,000</span></span></p>
          </div>
            </div>
            
          </div>

          <div className='bg-white shadow-2xl'>
            <img className='h-[19rem] w-full object-cover object-top' src="images/campaign-3.png" alt="compaign" />
            <div className='px-8 py-8'>
            <span>by Tazim</span>
            <h2 className='text-3xl font-bold'>Lorem Ipsum</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas vel, velit fugit rerum saepe, delectus odit accusantium quod accusamus a fuga, alias harum. Nulla error non dolorem voluptas porro eos.</p>
            <div className="w-full my-6 rounded-full h-2.5 bg-green-50">
            <div className="bg-green-600 h-2.5 w-[45%] rounded-full"></div>
            <p className='py-1'><span className='text-green-600 mx-1 text-lg'>Raised</span><span className='text-xl text-green-600 font-medium'>Rs 18,000</span><span className='float-right'><span className='text-lg'>Goal</span> <span className='text-xl font-medium'>Rs 40,000</span></span></p>
          </div>
            </div>
            
          </div>

          <div className='bg-white shadow-2xl'>
            <img className='h-[19rem] w-full object-cover object-top' src="images/campaign-1.png" alt="compaign" />
            <div className='px-8 py-8'>
            <span>by Tazim</span>
            <h2 className='text-3xl font-bold'>Lorem Ipsum</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas vel, velit fugit rerum saepe, delectus odit accusantium quod accusamus a fuga, alias harum. Nulla error non dolorem voluptas porro eos.</p>
            <div className="w-full my-6 rounded-full h-2.5 bg-green-50">
            <div className="bg-green-600 h-2.5 w-[45%] rounded-full"></div>
            <p className='py-1'><span className='text-green-600 mx-1 text-lg'>Raised</span><span className='text-xl text-green-600 font-medium'>Rs 18,000</span><span className='float-right'><span className='text-lg'>Goal</span> <span className='text-xl font-medium'>Rs 40,000</span></span></p>
          </div>
            </div>
            
          </div>
          <div className='bg-white shadow-2xl'>
            <img className='h-[19rem] w-full object-cover object-top' src="images/campaign-2.png" alt="compaign" />
            <div className='px-8 py-8'>
            <span>by Tazim</span>
            <h2 className='text-3xl font-bold'>Lorem Ipsum</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas vel, velit fugit rerum saepe, delectus odit accusantium quod accusamus a fuga, alias harum. Nulla error non dolorem voluptas porro eos.</p>
            <div className="w-full my-6 rounded-full h-2.5 bg-green-50">
            <div className="bg-green-600 h-2.5 w-[45%] rounded-full"></div>
            <p className='py-1'><span className='text-green-600 mx-1 text-lg'>Raised</span><span className='text-xl text-green-600 font-medium'>Rs 18,000</span><span className='float-right'><span className='text-lg'>Goal</span> <span className='text-xl font-medium'>Rs 40,000</span></span></p>
          </div>
            </div>
            
          </div>

          <div className='bg-white shadow-2xl'>
            <img className='h-[19rem] w-full object-cover object-top' src="images/campaign-3.png" alt="compaign" />
            <div className='px-8 py-8'>
            <span>by Tazim</span>
            <h2 className='text-3xl font-bold'>Lorem Ipsum</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas vel, velit fugit rerum saepe, delectus odit accusantium quod accusamus a fuga, alias harum. Nulla error non dolorem voluptas porro eos.</p>
            <div className="w-full my-6 rounded-full h-2.5 bg-green-50">
            <div className="bg-green-600 h-2.5 w-[45%] rounded-full"></div>
            <p className='py-1'><span className='text-green-600 mx-1 text-lg'>Raised</span><span className='text-xl text-green-600 font-medium'>Rs 18,000</span><span className='float-right'><span className='text-lg'>Goal</span> <span className='text-xl font-medium'>Rs 40,000</span></span></p>
          </div>
            </div>
            
          </div>
        </div>

        <div className='my-8 lg:mx-6 mx-9 lg:mt-[14rem]'>
          <span className='lg:text-4xl text-2xl break-normal'>Recent Post</span>
          <a className='lg:text-2xl text-xl float-right text-[#008837]' href="#">See all</a>
        </div>
        <div className='lg:grid space-y-5 lg:space-y-0 gap-6 lg:grid-cols-3 mx-4'>
          <div className='bg-white rounded-lg py-7'>
            <div className='flex mx-5 py-6'>
            <img src="images/profile.png" alt="profile_pic" />
            <div className='lg:mt-5 ml-5'>
            <span className='uppercase font-medium'>Me UI UX Designer</span><br />
            <span className='text-gray-300'>45 min</span>
            </div>
            </div>
            <div>
              <img className='object-cover w-full lg:w-[22rem] object-top lg:h-[19rem]' src="images/post-1.png" alt="card-img" />
              <p className='text-2xl py-4 px-3'>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
            </div>
          </div>
          <div className='bg-white rounded-lg py-7'>
            <div className='flex mx-5 py-6'>
            <img src="images/profile.png" alt="profile_pic" />
            <div className='lg:mt-5 ml-5'>
            <span className='uppercase font-medium'>Me UI UX Designer</span><br />
            <span className='text-gray-300'>45 min</span>
            </div>
            </div>
          <div>
            <img className='object-cover w-full lg:w-[22rem] object-top lg:h-[19rem]' src="images/post-2.png" alt="card-img" />
            <p className='text-2xl py-4 px-3'>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
          </div>
          </div>
          <div className='bg-white rounded-lg py-7'>
            <div className='flex mx-5 py-6'>
            <img src="images/profile.png" alt="profile_pic" />
            <div className='lg:mt-5 ml-5'>
            <span className='uppercase font-medium'>Me UI UX Designer</span><br />
            <span className='text-gray-300'>45 min</span>
            </div>
            </div>
          <div className=''>
          <img className='object-cover w-full lg:-w-[22rem] object-top lg:h-[19rem]' src="images/post-3.png" alt="card-img" />
          <p className='text-2xl py-4 px-3'>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
          </div>
          </div>
        </div>


        <div className='mx-2 rounded-2xl'>
          <h1 className='lg:text-5xl text-3xl py-9 text-center bg-[#EDEDED]'>What We Do</h1>
          <div className='lg:grid lg:grid-cols-2 lg:px-20 px-4'>
          <div className='lg:flex sm:flex py-2'>
          <div className='m-14 md:m-0'>
            <img className='bg-white p-2 rounded-2xl' width="380" height="380" src="images/charity.svg" alt="charity_logo" loading='lazy' decoding='async' />
          </div>
          <div className='lg:ml-9 text-center sm:text-left md:text-left'>
            <h4 className='text-3xl pb-4 py-4 lg:mt-0 text-[#008837]'>Fund&nbsp;raising for neady</h4>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse, odio voluptas. Sed deserunt nisi odio velit hic. Lorem ipsum dolor sit amet consectetur adipisicing elit</p>
          </div>
          </div>

          <div className='lg:flex py-2 sm:flex'>
          <div className='m-14 md:m-0'>
            <img className='bg-white p-2 rounded-2xl' width="380" height="380" src="images/reporting.svg" alt="charity_logo" />
          </div>
          <div className='lg:ml-9 text-center sm:text-left md:text-left'>
            <h4 className='text-3xl pb-4 py-4 lg:mt-0 text-[#008837]'>Crime reporting</h4>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse, odio voluptas. Sed deserunt nisi odio velit hic. Lorem ipsum dolor sit amet consectetur adipisicing elit</p>
          </div>
          </div>

          <div className='lg:flex py-2 sm:flex'>
          <div className='m-14 md:m-0'>
            <img className='bg-white p-2 rounded-2xl' width="380" height="380" src="images/empowerment.svg" alt="charity_logo" />
          </div>
          <div className='ml-9 sm:text-left md:text-left'>
            <h4 className='text-3xl pb-4 py-4 text-[#008837]'>Youth empowerment</h4>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse, odio voluptas. Sed deserunt nisi odio velit hic. Lorem ipsum dolor sit amet consectetur adipisicing elit</p>
          </div>
          </div>

          <div className='lg:flex py-2 sm:flex'>
          <div className='m-14 md:m-0'>
            <img className='bg-white p-2 rounded-2xl' width="380" height="380" src="images/social.svg" alt="charity_logo" />
          </div>
          <div className='ml-9 text-center sm:text-left md:text-left'>
            <h4 className='text-3xl pb-4 py-4 text-[#008837]'>Corporate social responsibility</h4>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse, odio voluptas. Sed deserunt nisi odio velit hic. Lorem ipsum dolor sit amet consectetur adipisicing elit</p>
          </div>
          </div>

          <div className='lg:flex py-2 sm:flex'>
          <div className='m-14 md:m-0'>
            <img className='bg-white p-2 rounded-2xl' width="380" height="380" src="images/women.svg" alt="charity_logo" />
          </div>
          <div className='ml-9 text-center sm:text-left md:text-left'>
            <h4 className='text-3xl pb-4 py-4 text-[#008837]'>Women security</h4>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse, odio voluptas. Sed deserunt nisi odio velit hic. Lorem ipsum dolor sit amet consectetur adipisicing elit</p>
          </div>
          </div>

          <div className='lg:flex py-2 sm:flex'>
          <div className='m-14 md:m-0'>
            <img className='bg-white p-2 rounded-2xl' width="380" height="380" src="images/community.svg" alt="charity_logo" />
          </div>
          <div className='ml-9 text-center sm:text-left md:text-left'>
            <h4 className='text-3xl pb-4 py-4 text-[#008837]'>Comunity Building</h4>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse, odio voluptas. Sed deserunt nisi odio velit hic. Lorem ipsum dolor sit amet consectetur adipisicing elit</p>
          </div>
          </div>

          <div className='lg:flex py-2 sm:flex'>
          <div className='m-14 md:m-0'>
            <img className='bg-white p-2 rounded-2xl' width="380" height="380" src="images/charity.svg" alt="charity_logo" />
          </div>
          <div className='ml-9 text-center sm:text-left md:text-left'>
            <h4 className='text-3xl pb-4 py-4 text-[#008837]'>Charity</h4>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse, odio voluptas. Sed deserunt nisi odio velit hic. Lorem ipsum dolor sit amet consectetur adipisicing elit</p>
          </div>
          </div>

          <div className='lg:flex py-2 sm:flex'>
          <div className='m-14 md:m-0'>
            <img className='bg-white p-2 rounded-2xl' width="380" height="380" src="images/consultation.svg" alt="charity_logo" />
          </div>
          <div className='ml-9 text-center sm:text-left md:text-left'>
            <h4 className='text-3xl py-4 pb-4 text-[#008837]'>Socila Consultation</h4>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse, odio voluptas. Sed deserunt nisi odio velit hic. Lorem ipsum dolor sit amet consectetur adipisicing elit</p>
          </div>
          </div>
          </div>
        </div>


        <div className='lg:mt-36 md:mt-4 bg-[#008837] py-20 mx-4 rounded-2xl '>
          <h1 className='lg:text-6xl md:text-4xl text-center lg:font-light text-white'>Ready to start Compaign</h1>
          <div className='text-center pt-11'>
          <button className='bg-white text-[#008837] lg:text-2xl py-1 rounded-full lg:py-4 px-8 lg:px-16 '>Start Campaign</button>
          </div>
        </div>

        <div className='mt-2 mx-4 sm:pl-16 lg:px-32 bg-[#EDEDED]'>
          <h3 className='uppercase py-5 md:mx-24 sm:text-3xl text-3xl sm:py-5 text-[#008837]'>Our&nbsp;volunteers</h3>

          <div className='flex pb-5 mt-11 md:mx-4 px-4 bg-white'>
            <div className=''>
            <h4 className='uppercase md:text-3xl text-2xl md:py-3 pt-16 italic'>me ui ux Designer</h4>
            <h5 className='md:text-3xl text-xl text-sky-600 py-3'>blogger41915@gmail.com</h5>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ipsa similique doloribus quos debitis esse!</p>
            </div>
            <div>
              <img className='rounded-tl-[20px] lg:rounded-tl-[120px]  sm:rounded-tl-[60px] lg:w-[20rem] w-full' src="images/volunteer.png" alt="volunteer" />
            </div>
          </div>
        </div>

        <div className='md:flex sm:flex-row flex-col  justify-center bg-[#FEF7EB] py-9 mt-16'>
          <div>
          <h4 className='sm:text-3xl text-center sm:text-left text-xl pb-7 sm:pb-0 mx-12'>Subscribe&nbsp;to&nbsp;get <br /> information</h4>
          </div>
          <div className='px-14 sm:px-0'>
            <g>
              <input className='py-3 lg:py-5 px-2 lg:w-[16rem] sm:w-[8rem] w-[15rem] md:px-4' type="email" placeholder='Email Address' />
              <input className='bg-[#FFC444] lg:py-5 lg:w-[8rem] sm:w-[8rem] px-2 w-[15rem] cursor-pointer py-3 text-white md:px-3' type="submit" value="SUBSCRIBE" />
            </g>
          </div>
        </div>
      </main>
    </>
  )
}
